name: flutter_inject
description: Flutter Injecion Examples
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: ^5.5.0
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.2
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
